import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,

} from '@clerk/nextjs'

import ConvexClientProvider from "@/components/ConvexClientProvider";
import UserSyncWrapper from "@/components/UserSyncWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Scholrpark",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider signInFallbackRedirectUrl={"/dashboard"}
          signUpFallbackRedirectUrl={"/dashboard"}>
          <ConvexClientProvider>            <UserSyncWrapper>
            {children}
          </UserSyncWrapper></ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
